[package]
name = "Hulk_Compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = { version = "0.23.0", features = ["lexer"] }
logos = "0.16.1"

[build-dependencies]
lalrpop = "0.23.0"
